### ISSUE TITLE
Suggestion: Make the thickness of the upper and lower borders consistent

### ISSUE THREAD

**Issue by roottool** [eslint/new.eslint.org#121]
### What problem do you want to solve?

I want to solve my first impression for a first impression of the website viewer. It is that I felt the website has a progress bar area at top of the website. 

I thought that this has occurred by two reasons.
First, the current website header doesn't consistent the upper and lower borders. The upper border has `4px` but the lower border has `1px`.
Additionaly, the color of this upper border is different from the lower border and a background color in the website. 

### Code pointer

https://github.com/eslint/new.eslint.org/blob/c3360e64aa31c400c7264c56653c2406f86f4973/src/assets/scss/_header.scss#L1-L6

### What do you think is the correct solution?

I think that this solution has two options.

- Consistent the upper and lower borders
- Remove the upper border

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Thanks for the feedback. This was an intentional design decision. The upper border is meant to separate the page from the browser chrome — if it’s too thin, then you won’t see it.

The lower border is meant to separate the navigation area from the content of the page. A thicker border there would call too much attention to an unimportant area.

**Comment by roottool** [comment]
Thanks for sharing your intentions with me. I close this issue since there is no need to modify it.
